<a href="https://colab.research.google.com/github/amityadav757330/DS-ML-AI/blob/main/DS_ML_AI_Batch_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Basics of Python

In [ ]:
# @title Comments
# Single Line Comment
a = 2
b = 3
c = a + b # c is a variable and value of a and b has been added
'''
Multi Line Comment
Adding two number and storing the value in c
(This statement will be completly ignored by python)
'''

In [ ]:
# @title Print Function
# Syntax for Print Function
a = 10
b = 20
sum = a + b
print(sum) # Valid syntax
Print(sum) # Invalid syntax
# Press Ctrl + Enter to run

30


In [ ]:
# Printing Hello World
print('Hello World')
print("Hello World")
n1 = 10
n2 = 20
sum = n1 + n2
print(sum)
print('sum')
# Anything and everything that is mentioned inside the single/double qutoes will be printed as it is.

Hello World
Hello World
30
sum


In [ ]:
# There are two parameters in print function
'''
1) end parameter
2) sep parameter
'''
# Print both statments in a single line
print('Hello world', end = ' ') #Default value of end is '\n'(new line)
print('How are You?')
# Seperate two staments with @
print('rinex','gmail.com', sep = '@') # Default value of sep is ' ' (Space)

Hello world How are You?
rinex@gmail.com


In [ ]:
# Anything that can store any value in programming language is termed as variable
a = 10 # Here 'a' is a variable
message = 'Hello World' # Here 'message' is a variable
print(a)
print(message)
'''
Rules to write a variable
1) You cannot start the variable name with a number but you continue with it.
Ex : 1a - Invalid , a1 - Valid
2) We cannot use keywords as variable name.
Ex : print = 10 (Invalid)
3) Case sensitive
Ex :
a = 10
print(A) # Invalid syntax
a = 10
print(a) # Valid Syntax
'''

10
Hello World


'\nRules to write a variable\n1) You cannot start the variable name with a number but you continue with it.\nEx : 1a - Invalid , a1 - Valid\n2) We cannot use keywords as variable name.\nEx : print = 10 (Invalid)\n3) Case sensitive\nEx :\na = 10\nprint(A) # Invalid syntax\na = 10\nprint(a) # Valid Syntax\n'

# BASIC OPERATORS IN PYTHON

1) Arithmetic Operators

2) Comparison Operators

3) Logical Operators

4) Assignment Operators

In [ ]:
# @title Arithmetic Operators
'''
1) Addition (+)
2) Subtraction (-)
3) Division (/)
4) Multiplication (*)
5) Modulus (Remainder) (%)
6) Floor Division (//)
7) Exponent (**)
'''
a = 10
b = 5
sum = a + b
print("Sum is", sum)
diff = a - b
print("Difference is", diff)
qnt = a / b
print("Quotient is", qnt)
prod = a * b
print("PRoduct is", prod)

num1 = 5
num2 = 2
mod = num1 % num2
print("Remainder is", mod)
floor = num1 // num2
print("Quotient is", floor)

base = 9
power = 8
pow = base ** power
print("Base is", base, "Power is", power, "Output", pow)

Sum is 15
Difference is 5
Quotient is 2.0
PRoduct is 50
Remainder is 1
Quotient is 2
Base is 9 Power is 8 Output 43046721


In [ ]:
# @title Comparison Operators
'''
1) Equal to (==)
2) Not Equal (!=)
3) Greater than (>)
4) Greater than or equal to (>=)
5) Lesser than (<)
6) Lesser than or equal to (<=)
'''
num1 = 2
num2 = 2
ex1 = (num1 == num2)
print(ex1)
ex2 = (num1 != num2)
print(ex2)

num3 = 2
num4 = 5
ex3 = (num3 >= num4)
print(ex3)
ex4 = (num3 <= num4)
print(ex4)

True
False
False
True


In [ ]:
# @title Logical Operators
'''
1) Logical AND (and)
2) Logical OR (or)
3) Logical NOT (not)
'''
# Get only the number that is greater than 5 and less than 10
num = int(input("Enter a number")) # Input function by deafult will take string datatype
cond = (num > 5) and (num < 10)
print(cond)
# Get output as True if the enetered age is greater than or equal to 18
age = int(input("Enetr your age"))
cond1 = (age > 18) or (age == 18)
print(cond1)

# Logical not is used to reverse the output
cond = False
print(not(cond))

True


In [ ]:
# @title Assignment Operators
'''
0) Assignment (=)
1) Addition Assigment(+=)
2) Subtraction Assigment(-=)
3) Division Assigment(/=)
4) Multiplication Assigment(*=)
5) Modulus Assigment(Remainder) (%=)
6) Floor Division Assigment(//=)
7) Exponent Assigment(**=)
'''
num = 10
#num = num + 1
num -= 1
print(num)

9


# CONDITIONAL STATEMENT

1) IF statement

2) IF else Statement

3) IF elif else Statement

In [ ]:
# @title Syntax of if statement
if condition:
  statments
elif condition:
  statements
  ..
  ..
  ..
  ..
else:
  statments

In [ ]:
# @title Example 1
# Check if the number is greater than 0 or not.
num = int(input("Enter a number"))
if num > 0:
  print("Number is greater than 0")
else:
  print("Number is lesser than 0")

Enter a number-7
Number is lesser than 0


In [ ]:
# @title Example 2
# Check if the number is +ve or -ve
num = int(input("Enter a number"))
if num > 0:
  print("Number is +ve")
elif num == 0:
  print("Number is zero")
else:
  print("Number is -ve")

Enter a number0
Number is zero


In [ ]:
# @title Example 3
# Check if you are admin, then you have admin privilege else you have no access
username = input("Enter username")
admin_username = 'admin@123'
if username == admin_username:
  print("Welcome Admin Kindly Enter your password")
  password = input("Enter admin Password")
  admin_password = 'pass@432'
  if password == admin_password:
    print("Welcome Admin, You have admin privilage")
  else:
    print("Invalid Admin Password")
else:
  print("Invalid Admin Username")

Enter usernameadmin@123
Welcome Admin Kindly Enter your password
Enter admin Passwordhdcudciywvc
Invalid Admin Password


In [ ]:
# @title Example 4
# Check if you user is eligible to vote (Age >= 18)
age = int(input("Enter your age"))
if age >= 18:
  print("Age:",age,"You are eligible to vote")
else:
  print("You require",18-age,"more years to vote")

Enter your age15
You require 3 more years to vote


In [ ]:
# @title Example 5
# Check if the number is Even or Odd
num = int(input("Enter any number"))
if num % 2 == 0:
  print("Even")
else:
  print("Odd")

Enter any number4
Even


In [ ]:
# @title Example 6
# Check if the number is Factor of 7
num = int(input("Enter any number"))
if num % 7 == 0:
  print("Factor of 7")
else:
  print("Not a factor of 7")

Enter any number15
Not a factor of 7


In [ ]:
# Exercise 1
# If the employee is working in the company for more than 5 years then he/she will get a bonus of 50% to thier current salary
work_experience = int(input("Enter years of experience"))
if work_experience > 5:
  salary = float(input("Enter salary"))
  bonus = salary * 0.5
  print("Your years of experience is greater than 5 here is your total payout with bonus", salary + bonus)
else:
  print("No bonus")

Enter years of experience2
No bonus


In [ ]:
# Exercise 2
# If the electricty units is less than 100 then no charge, else if the electricity unit is greater than 100 and lesser than
# 200 then Rs.10 per unit. If the units is greater than 200 then Rs.15 per unit
units = float(input("Enter the no.of units"))
if units <= 100:
  print("No Charge")
elif units <= 200:
  print("Charges will be", (units - 100) * 10, "Beacase you have used", units - 100,"extra unit")
else:
  print("Charges will be", 1000 +(units - 200) * 15, "Beacase you have used", units - 100,"extra unit")

Enter the no.of units202
Charges will be 1030.0 Beacase you have used 102.0 extra unit


In [ ]:
units < 100 - No Charge
units > 100 and units <= 200 - Each extra unit rupees 10
units > 200 - Each extra unit after 200 rupees 15

units = 202
Charge = 1000 + 15 = 1030

In [ ]:
# Exercise 3
# BMI Calculator
# BMI = (Weight(KG)) / (Height(M) ** 2)
# BMI < 18.5 Then Underweight
# BMI between 18.5 and 24.9 then normal weight
# BMI between 24.9 and 29.9 then overweight
# BMI > 29.9 Obese
height_m = float(input("Enter the height in meters"))
weight_kg = float(input("Enter the weight in Kgs"))
BMI = weight_kg / (height_m ** 2)
if BMI < 18.5:
  #print("BMI Score is", BMI, "Underweight")
  print(f"BMI Score is {BMI} Underweight")
elif BMI >=18.5 and BMI < 24.9:
  print(f"BMI Score is {BMI} Normal Weight")
elif BMI >=24.9 and BMI < 29.9:
  print(f"BMI Score is {BMI} Over Weight")
else:
  print(f"BMI Score is {BMI} Obese")

Enter the height in meters1.2
Enter the weight in Kgs100
BMI Score is 69.44444444444444 Obese


In [ ]:
# Exercise 4
# Find whether the character is a vowel or a consonant
char = input("Enter any letter")
char_lower = char.lower()
vowels = ['a','e','i','o','u']
if char_lower in vowels:
  print("Given letter is Vowel")
else:
  print("Given letter is Consonant")

Enter any letterG
Given letter is Consonant


# Datatype

1) Boolean

2) Number (int/float)

3) String

4) List

5) Dictionary

In [ ]:
# Boolean Datatype
a = True
b = False
print(type(a))

<class 'bool'>


In [ ]:
# Number Datatype
a = 1
b = 1.1
print(type(b))

<class 'float'>


In [ ]:
# String Datatype
a = 'Hello World'
print(type(a))

# Access only H
print(a[0])
# Access only d
print(a[-1])
# Access only Hello
print(a[0:5]) # Syntax [start:stop-1]
# Access only World
print(a[6:])

<class 'str'>
H
d
Hello
World


In [ ]:
# Function in String Datatype
str1 = 'My NamE is RiNex'
# Lower
print(str1.lower())
# Upper
print(str1.upper())
# Length
print(len(str1))
# Replace
print(str1.replace('RiNex','Max'))

my name is rinex
MY NAME IS RINEX
16
My NamE is Max


In [ ]:
# List
emp_name = ['Sam','John','Ram','Adam']
print(emp_name)

# Accessing List Elements - Sam
print(emp_name[0])

# Accessing List Elements - Adam
print(emp_name[-1])

# Accessing List Elements - John and Ram
print(emp_name[1:3])

['Sam', 'John', 'Ram', 'Adam']
Sam
Adam
['John', 'Ram']


In [ ]:
# Dictionary Datatype
'''
employees = ['Adam',25,'John',28,'Ram',26]
# Find the age of John
print(employees[3])
'''
employees = {'Adam':20, 'John' : 28, 'Ram' : 26} # key:value pair
print(employees['Ram'])
# Display all employees names (keys)
print(employees.keys())
# Display all employees age (value)
print(employees.values())
# Display all employees age (name,value)
print(employees.items())

26
dict_keys(['Adam', 'John', 'Ram'])
dict_values([20, 28, 26])
dict_items([('Adam', 20), ('John', 28), ('Ram', 26)])


In [ ]:
# @title Exercise
# User Authentication
database = {
            'user1' : '123456',
            'user2' : '123@abc',
            'user3' : '654321'
           }

username = input("Enter your Username")
if username in database.keys():
  password = input("Enter your Password")
  if password == 123456:
    print("Welcome",username)
  else:
    print("Invalid Password")
else:
  print("Invalid Username")

Enter your Usernameuser1
Enter your Password123456
Welcome user1


# Looping Statements

In [ ]:
'''
1) For loop (Whenever we know the no.of iterations)
2) While loop (Whenever we do not know the no.of iterations) - Infinite loop
'''

In [ ]:
# Syntax for loop
for intialization_variable in condition:
  statements

In [ ]:
# Syntax while loop
intialization_variable = value
while condition:
  statements

In [ ]:
# Print Hello 10 times
for i in range(10):
  print('Hello')

# i = 0 range(0:10)
# i = 1 range(0:10-1)
'''
.
.
.
.
.
'''
# i = 10 range(0:10))

Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello


In [ ]:
# Print Hello 10 times
i = 0
while i < 10:
  print('Hello')
  i += 1
  #i = i + 1

Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello


In [ ]:
# Print Number 0 to 10
for i in range(11):
  print(i)

0
1
2
3
4
5
6
7
8
9
10


In [ ]:
# Print Number 0 to 10
i = 0
while i <= 10:
  print(i)
  i += 1

0
1
2
3
4
5
6
7
8
9
10


In [ ]:
# Print Number 1 to 10
for i in range(1,11): # range(start,stop-1)
  print(i)

1
2
3
4
5
6
7
8
9
10


In [ ]:
# Print Number 1 to 10
i = 1
while i <= 10:
  print(i)
  i += 1

1
2
3
4
5
6
7
8
9
10


In [ ]:
# Print Number 5 to 10
for i in range(5,11,+1): # range(start,stop-1,stepsize)
  print(i)

5
6
7
8
9
10


In [ ]:
# Print Number 5 to 10
i = 5
while i <=10:
  print(i)
  i += 1

5
6
7
8
9
10


In [ ]:
# Print Number 10 to 1
for i in range(10,0,-1): # range(start,stop-1,stepsize)
  print(i)

10
9
8
7
6
5
4
3
2
1


In [ ]:
# Print Number 10 to 1
i = 10
while i > 0:
  print(i)
  i -= 1

10
9
8
7
6
5
4
3
2
1


In [ ]:
# Print 5 to 50 but only the 5 multiples
for i in range(5,51,+5):
  print(i)

5
10
15
20
25
30
35
40
45
50


In [ ]:
# Print 5 to 50 but only the 5 multiples
i = 5
while i <= 50:
  print(i)
  i += 5

5
10
15
20
25
30
35
40
45
50


In [ ]:
# Print 50 to 5 but only the 5 multiples
for i in range(50,4,-5):
  print(i)

50
45
40
35
30
25
20
15
10
5


In [ ]:
# Print 50 to 5 but only the 5 multiples
i = 50
while i >= 5:
  print(i)
  i -= 5

50
45
40
35
30
25
20
15
10
5


In [ ]:
# Print 10 to 170 but only the 13 multiples
for i in range(10,171):
  if i % 13 == 0:
    print(i)

13
26
39
52
65
78
91
104
117
130
143
156
169


In [ ]:
# Print 10 to 170 but only the 13 multiples
i = 10
while i <= 170:
  if i % 13 == 0:
    print(i)
  i += 1

13
26
39
52
65
78
91
104
117
130
143
156
169


In [ ]:
'''
*
*
*
*
*
'''
for i in range(5):
  print('*', end = '\n')

*
*
*
*
*


In [ ]:
'''
* * * * *
'''
for i in range(5):
  print('*', end = ' ')

* * * * * 

In [ ]:
'''
*****
*****
*****
*****
*****
'''
for i in range(5):
  print("*" * 5)

*****
*****
*****
*****
*****


In [ ]:
'''
*
**
***
****
*****
'''
for i in range(1,6):
  print("*" * i)

*
**
***
****
*****


In [ ]:
'''
*****
****
***
**
*
'''
for i in range(5,0,-1):
  print("*" * i)

*****
****
***
**
*


In [ ]:
# @title Nested For Loop
'''
1
2 2
3 3 3
4 4 4 4
5 5 5 5 5
'''
for i in range(1,6): # Rows
  for j in range(i): # Columns
    print(i, end = " ")
  print(end = '\n')

1 
2 2 
3 3 3 
4 4 4 4 
5 5 5 5 5 


In [ ]:
'''
1
1 2
1 2 3
1 2 3 4
1 2 3 4 5
'''
for i in range(1,6): # Rows
  for j in range(i): # Columns
    print(j + 1, end = " ")
  print(end = '\n')

1 
1 2 
1 2 3 
1 2 3 4 
1 2 3 4 5 


In [ ]:
# Find the sum of the list using for loop
num_list = [34,34,6,56,34,656,67,54,5,7,98,32]
sum = 0
for i in num_list:
  sum = sum + i # sum += i
print(sum)

1083


In [ ]:
# Program to find factorial of a number using while loop
num = int(input("Enter the value"))
fact = 1
while num: # True
  fact = fact * num
  num = num - 1
print(fact)

Enter the value4
24


In [ ]:
# Check prime number
num = int(input("Enter a number"))
if num <= 1:
  print("Number is not prime")
else:
  is_prime = True # Assuming it's prime
  for i in range(2, num):
    if num % i == 0: # 9 % 2 == 0
      is_prime = False
      break

  if is_prime:
    print(num, 'is a prime number')
  else:
    print(num, 'is not a prime number')

Enter a number9
9 is not a prime number


In [ ]:
# Display Menu Program
while True:
  print("Calculator ")
  print("Option 1 - Sum")
  print("Option 2 - Difference")
  print("Option 3 - Product")
  print("Option 4 - Quotient")
  print("Option 5 - Quit")
  option = int(input("Enter your choice"))
  num1 = int(input("Enter number 1"))
  num2 = int(input("Enter number 2"))
  if option == 1:
    sum = num1 + num2
    print("Sum", sum)
  elif option == 2:
    sum = num1 - num2
    print("Difference",sum)
  elif option == 3:
    sum = num1 * num2
    print("Product",sum)
  elif option == 4:
    sum = num1 / num2
    print("Quotient",sum)
  elif option == 5:
    print("Thank you")
    break
  else:
    print("Invalid choice")

Calculator 
Option 1 - Sum
Option 2 - Difference
Option 3 - Product
Option 4 - Quotient
Option 5 - Quit
Enter your choice1
Enter number 15
Enter number 22
Sum 7
Calculator 
Option 1 - Sum
Option 2 - Difference
Option 3 - Product
Option 4 - Quotient
Option 5 - Quit
Enter your choice2
Enter number 15
Enter number 22
Difference 3
Calculator 
Option 1 - Sum
Option 2 - Difference
Option 3 - Product
Option 4 - Quotient
Option 5 - Quit
Enter your choice3
Enter number 15
Enter number 22
Product 10
Calculator 
Option 1 - Sum
Option 2 - Difference
Option 3 - Product
Option 4 - Quotient
Option 5 - Quit
Enter your choice5
Enter number 15
Enter number 22
Thank you


In [ ]:
# @title Functions
'''
In python, a function is a reusable block of code that performs a specific task or a set of task.
'''

In [ ]:
# @title Example 1
# Code to return whether the given number is odd or eve
def oddeve(num):
  if num % 2 == 0:
    print("Even")
  else:
    print("Odd")

In [ ]:
# Code to return whether the given number is odd or eve from the user
def oddeve():
  while True:
    num = int(input("Enter a number"))
    if num == 0:
      print("Number is 0")
      break
    elif num % 2 == 0:
      print("Even")

    else:
      print("Odd")

    # 1 2 3 6 8 9

In [ ]:
oddeve()

Enter a number1
Odd
Enter a number2
Even
Enter a number3
Odd
Enter a number0
Number is 0


In [ ]:
# @title Lambda Functions
'''def add(x,y):
  sum = x + y
  print(sum)'''

def addsub(x,y):
  sum = x + y
  print(sum)
  sub = x - y
  print(sub)
add = lambda x,y : x + y
# We can only mention one expression at a time.

In [ ]:
'''def greet():
  print("Hello Sir/Madam")
'''
greet = lambda : "Hello Sir/Madam"

In [ ]:
greet()

'Hello Sir/Madam'

# Numpy

In [ ]:
# NumPy stands for Numerical python.
# NumPy is a python library used for working with arrays.
# Arrays is collection of objects.

In [ ]:
# @title Steps to Import numpy and to use it
# Step 1: Import numpy library
import numpy as np
# Step 2: Convert list into a array
x = [1,2,3]
arr = np.array(x)
print(x)
print(arr)

[1, 2, 3]
[1 2 3]


In [ ]:
# @title Example 1
# Add +1 to each list elements
x = [1,2,3,4,5]
import numpy as np
arr = np.array(x)
print(arr + 1)

[2 3 4 5 6]


In [ ]:
# @title Example 2
# Mathematical Operations using Numpy
x = [1,6,9,5,8]
# Find Remainder of each value when it is divided by 2
import numpy as np
arr = np.array(x)
print(arr % 2)
# Find square of each array elements
print(arr ** 2)

[1 0 1 1 0]
[ 1 36 81 25 64]


In [ ]:
# @title Example 3
# Converting a list into an array without declaring the list
import numpy as np
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])
print(arr1, arr2)
# Find Maximum value out of array 1
print(arr1.max())
print(np.max(arr1))
# Find Minimum value out of array 2
print(arr2.min())
print(np.min(arr2))
# Find Average value out of array 1
print(arr1.mean())
print(np.mean(arr1))

[1 2 3 4 5] [ 6  7  8  9 10]
5
5
6
6
3.0
3.0


In [ ]:
# @title Example 4
# Find the dimension of the array
x = [1,2,3,4,5]
arr = np.array(x)
print(arr.ndim)

1


In [ ]:
# @title Example 5
# Create 2D array
x = [[1,2,3,4,5],
     [6,7,8,9,10]]
arr = np.array(x)
print(arr.ndim)

2


In [ ]:
# @title Steps to create multi dimensional arrays
# Step 1: Create Outermost array
x = []
# Step 2: Create Inner Array
x = [[],[]]
# Step 3: Create Inner most array
x = [[[],[]],[[],[]]]

In [ ]:
# @title Random Number Library
# Exploring random number library from numpy
import numpy as np
from numpy import random
x = (random.randint(10))
arr = np.array(x)
print(arr)

5


In [ ]:
# @title Example 1
# Create 1D array using random library
x = (random.randint(10, size = (5)))
arr = np.array(x)
print(arr)

[5 9 3 9 0]


In [ ]:
# @title Example 2
# Create 2D array using random library
x = (random.randint(11, size = (5,3))) # rows, columns
arr = np.array(x)
print(arr)

[[ 7  9 10]
 [ 5  1  8]
 [ 4  9  7]
 [ 3  2  3]
 [ 5  4  1]]


In [ ]:
# @title Example 3
# Create 3D array using random library
x = (random.randint(10, size = (5,4,3))) # Inner arrays, rows, columns
arr = np.array(x)
print(arr)

[[[1 3 6]
  [1 8 1]
  [6 7 1]
  [6 2 3]]

 [[6 0 1]
  [0 8 3]
  [6 1 6]
  [6 7 1]]

 [[2 4 9]
  [0 0 3]
  [3 5 8]
  [4 7 3]]

 [[3 8 5]
  [6 8 9]
  [1 8 6]
  [1 0 9]]

 [[6 9 1]
  [5 0 1]
  [1 1 0]
  [7 4 6]]]


In [ ]:
# @title A-Range function
'''
It is similar to range function but returns array
'''
import numpy as np
x = np.arange(1,11) # start,end-1
print(x)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
# @title Example 1
# Change the datatype
x = np.arange(1,11, dtype = float)
print(x)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [ ]:
# @title Example 3
# Print the factors of 5 to 50
x = np.arange(5,51,5)
print(x)

[ 5 10 15 20 25 30 35 40 45 50]


In [ ]:
# @title Example 4
# Print array containing ones
x = np.ones(10, dtype = int)
print(x)

[1 1 1 1 1 1 1 1 1 1]


In [ ]:
# @title Example 5
# Print 2D array containing zeros
x = np.zeros([2,4], dtype = int)
print(x)

[[0 0 0 0]
 [0 0 0 0]]


In [ ]:
# @title Example 6
# Print Identity Matrix
x = np.identity(4, dtype = int)
print(x)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [ ]:
# @title Example 7
x = np.eye(4, k = -1, dtype =int) # k = offset value
print(x)

[[0 0 0 0]
 [1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]]


In [ ]:
# Convert 1D array into 2D array
x = np.arange(10)
print(x)
'''
Factors 0f 20
2 * 10
10 * 2
4 * 5
5 * 4
1 * 20
20 * 1
'''
reshaped = x.reshape(5,2)
print("Reshaped Array", reshaped)
print("Reshaped array dimension", reshaped.ndim)

[0 1 2 3 4 5 6 7 8 9]
Reshaped Array [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
Reshaped array dimension 2


In [ ]:
# Convert 1D array into 3D array
import numpy as np
x = np.arange(20)
print("Original Array", x)
'''
5, 2, 2
2, 5, 2
'''
reshaped = x.reshape(2,5,2)
print("Reshaped array", reshaped)

Original Array [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
Reshaped array [[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]]


In [ ]:
# Convert 2D array into 3D array
x = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print("Original array",x)
print("Original array dimension", x.ndim)
'''
factors of 10
2, 5, 1
1,1,10
'''
reshaped = x.reshape(2,5,1)
print('Reshaped array', reshaped)

Original array [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Original array dimension 2
Reshaped array [[[ 1]
  [ 2]
  [ 3]
  [ 4]
  [ 5]]

 [[ 6]
  [ 7]
  [ 8]
  [ 9]
  [10]]]


In [ ]:
# Convert 2D array into 1D array
x = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print("Original array",x)
print("Original array dimension", x.ndim)
'''
10
'''
reshaped = x.reshape(10)
print("Reshaped array", reshaped)

Original array [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Original array dimension 2
Reshaped array [ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
# @title Accessing Array Elements
'''
1) Slicing
2) Integer Array Indexing
3) Boolean Array Indexing
'''

In [ ]:
# Slicing
import numpy as np
arr1 = np.array([1,2,3])
# Access only 2 from the given array
print(arr1[1])
# Access only 3 from the given array
print(arr1[2])
arr2 = np.array([[1,2,3],
                 [4,5,6]])
# Access only 1 from the given array
print(arr2[0][0])
# Access only 6 from the given array
print(arr2[1][2])

2
3
1
6


In [ ]:
# Integer Array Indexing
arr1 = np.array([1,2,3])
# Access only 2 from the given array
print(arr1[1])
arr2 = np.array([[1,2,3],
                 [4,5,6]])
# Access only 1 from the given array
print(arr2[0,0])
# Access only 2 from the given array
print(arr2[0,1])

2
1
2


In [ ]:
# Boolean Array Indexing
arr = np.array([[32,5,23,1,43,12,34,34,345,23,23],
                [12,34,34,23,23,34,76,54,76,87,56]])
print("Extract only those values which are greater than 70")
cond = (arr > 70)
print('Values that are greater than 70 are', arr[cond]) # [] is used to extract values from the array

Extract only those values which are greater than 70
Values that are greater than 70 are [345  76  76  87]


In [ ]:
arr = np.array([[32,5,23,1,43,12,34,34,345,23,23],
                [12,34,34,23,23,34,76,54,76,87,56]])
print("Extract only those values which are not divisible by 2 or basically extract odd numbers")
cond = (arr % 2 != 0)
print(arr[cond])

Extract only those values which are not divisible by 2 or basically extract odd numbers
[  5  23   1  43 345  23  23  23  23  87]


In [ ]:
# @title Student Report Dataset
import numpy as np
students_array = np.array([['Student_1', 59, 64, 94, 87, 81],

                          ['Student_2', 8, 56, 18, 58, 69],

                          ['Student_3', 7, 20, 60, 63, 42],

                          ['Student_4', 71, 94, 71, 68, 13],

                          ['Student_5', 89, 1, 16, 33, 40],

                          ['Student_6', 4, 25, 48, 41, 84],

                          ['Student_7', 3, 79, 46, 9, 71],

                          ['Student_8', 87, 77, 75, 15, 69],

                          ['Student_9', 61, 1, 48, 98, 23],

                          ['Student_10', 98, 60, 24, 66, 56],

                          ['Student_11', 58, 12, 75, 7, 98],

                          ['Student_12', 23, 62, 6, 35, 37],

                          ['Student_13', 14, 25, 87, 56, 8],

                          ['Student_14', 68, 1, 81, 11, 61],

                          ['Student_15', 11, 69, 35, 17, 66]], dtype=object)

In [ ]:
# @title Task 1
# Accessing all the names of the students
students_array[:, 0] # Rows, columns
# If we are accessing all the rows just mention : (This means it will start from the beginning and end at the last)

array(['Student_1', 'Student_2', 'Student_3', 'Student_4', 'Student_5',
       'Student_6', 'Student_7', 'Student_8', 'Student_9', 'Student_10',
       'Student_11', 'Student_12', 'Student_13', 'Student_14',
       'Student_15'], dtype=object)

In [ ]:
# @title Task 2
# Find the average of subject 1
sub1 = students_array[:, 1]
print("Average of Subject 1 is", sub1.mean())
print("Average of Subject 1 is", np.mean(sub1))

Average of Subject 1 is 44.06666666666667
Average of Subject 1 is 44.06666666666667


In [ ]:
# @title Task 3
# Find the average of subject 4
sub4 = students_array[:,4]
print("Average of Subject 4 is", sub4.mean())

Average of Subject 4 is 44.266666666666666


In [ ]:
# @title Task 4
# Find the average of student 7
student_7 = students_array[6, 1:].mean()
print("Average of Student 7 is", student_7)

Average of Student 7 is 41.6


In [ ]:
# @title Task 5
# Find the average of student 7 for subject 2 to 4
student_7 = students_array[6, 2:5].mean()
print("Average of Student 7 in Subject 2 to 4 is", student_7)

Average of Student 7 in Subject 2 to 4 is 44.666666666666664


In [ ]:
# @title Task 6
# Find the name and count of students where subject 1 marks is greater than subject 2 marks
sub1 = students_array[:,1]
sub2 = students_array[:,2]
cond = sub1 > sub2
print("Students who scored higher in subject 1 than subject 2 are",students_array[cond, 0]) # rows, columns
print("Count of students scored subject1 marks higher than subject 2 marks is", len(students_array[cond]))

Students who scored higher in subject 1 than subject 2 are ['Student_5' 'Student_8' 'Student_9' 'Student_10' 'Student_11'
 'Student_14']
Count of students scored subject1 marks higher than subject 2 marks is 6


In [ ]:
# @title Task 7
# Find the student average of first 10 students
first_10_stu = students_array[:10, 1:]
print('Student average of first 10 students', first_10_stu.mean(axis = 1)) # Axis = 1 means row wise average

# Find the subject average of first 10 students
first_10_stu = students_array[:10, 1:]
print('Subject average of first 10 students', first_10_stu.mean(axis = 0)) # Axis = 0 means Column wise average

Student average of first 10 students [77.0 41.8 38.4 63.4 35.8 40.4 41.6 64.6 46.2 60.8]
Subject average of first 10 students [48.7 47.7 50.0 53.8 54.8]


In [ ]:
# @title Task 8
# Find the Subject average of 1,3 and 4 subject.
sub_avg = students_array[:, [1,3,4]] # columns
print(sub_avg.mean(axis = 0))

[44.06666666666667 52.266666666666666 44.266666666666666]


In [ ]:
# @title Task 9
# Find the subject average of student 5 to student 14
sub_avg_5_to_14 = students_array[4:14, 1:]
print(sub_avg_5_to_14.mean(axis = 0))

[50.5 34.3 50.6 37.1 54.7]


In [ ]:
# @title Task 10
# Find all the student names who scored higher than student 15 in both subject1 and subject2
stu_15_sub_1 = students_array[14,1]
stu_15_sub_2 = students_array[14,2]
sub1 = students_array[:,1]
sub2 = students_array[:,2]
cond = (sub1 > stu_15_sub_1) & (sub2 > stu_15_sub_2)
print("Student 15 Subject 1 and 2 marks are", stu_15_sub_1,'and', stu_15_sub_2)
print(students_array[cond, 0:3])

Student 15 Subject 1 and 2 marks are 11 and 69
[['Student_4' 71 94]
 ['Student_8' 87 77]]


In [ ]:
# @title Task 11
# Find all the student names who scored higher than student 11 either in subject 1 or subject 5
stu_11_sub_1 = students_array[10,1]
stu_11_sub_5 = students_array[10,5]
sub1 = students_array[:,1]
sub5 = students_array[:,5]
cond = (sub1 > stu_11_sub_1) | (sub5 > stu_11_sub_5)
print("Student 11 Subject 1 and 5 marks are", stu_11_sub_1,'and', stu_11_sub_5)
print(students_array[cond, 0:3])

Student 11 Subject 1 and 5 marks are 58 and 98
[['Student_1' 59 64]
 ['Student_4' 71 94]
 ['Student_5' 89 1]
 ['Student_8' 87 77]
 ['Student_9' 61 1]
 ['Student_10' 98 60]
 ['Student_14' 68 1]]


In [ ]:
# @title Bank Customer Dataset
# Age , Employment , Marital Status, Balance, Personal Loan, Car Loan, Connection, Month of Join
import numpy as np
banking_array = np.array([[30.0, 'unemployed', 'married', 1787.0, 'no', 'no', 'cellular','oct'],

       [33.0, 'services', 'married', 4789.0, 'yes', 'yes', 'cellular','may'],

       [35.0, 'management', 'single', 1350.0, 'yes', 'no', 'cellular','apr'],

       [30.0, 'management', 'married', 1476.0, 'yes', 'yes', 'unknown','jun'],

       [59.0, 'blue-collar', 'married', 0.0, 'yes', 'no', 'unknown','may'],

       [35.0, 'management', 'single', 747.0, 'no', 'no', 'cellular','feb'],

       [36.0, 'self-employed', 'married', 307.0, 'yes', 'no', 'cellular','may'],

       [39.0, 'technician', 'married', 147.0, 'yes', 'no', 'cellular','may'],

       [41.0, 'entrepreneur', 'married', 221.0, 'yes', 'no', 'unknown','may'],

       [43.0, 'services', 'married', -88.0, 'yes', 'yes', 'cellular','apr'],

       [39.0, 'services', 'married', 9374.0, 'yes', 'no', 'unknown','may'],

       [43.0, 'admin.', 'married', 264.0, 'yes', 'no', 'cellular', 'apr'],

       [36.0, 'technician', 'married', 1109.0, 'no', 'no', 'cellular','aug'],

       [20.0, 'student', 'single', 502.0, 'no', 'no', 'cellular', 'apr'],

       [31.0, 'blue-collar', 'married', 360.0, 'yes', 'yes', 'cellular','jan'],

       [40.0, 'management', 'married', 194.0, 'no', 'yes', 'cellular','aug'],

       [56.0, 'technician', 'married', 4073.0, 'no', 'no', 'cellular','aug'],

       [37.0, 'admin.', 'single', 2317.0, 'yes', 'no', 'cellular', 'apr'],

       [25.0, 'blue-collar', 'single', -221.0, 'yes', 'no', 'unknown','may'],

       [31.0, 'services', 'married', 132.0, 'no', 'no', 'cellular','jul']], dtype=object)

In [ ]:
# @title Task 1
# Finding unique values from the employment column
np.unique(banking_array[:,1])

array(['admin.', 'blue-collar', 'entrepreneur', 'management',
       'self-employed', 'services', 'student', 'technician', 'unemployed'],
      dtype=object)

In [ ]:
# @title Task 2
# Find the count of customers who has taken a personal loan
cust_with_personal_loan = (banking_array[:,4] == 'yes')
np.count_nonzero(cust_with_personal_loan)

13

In [ ]:
# @title Task 3
# Find the count of cutomers who has connection and has taken car loan
conn = (banking_array[:,6] == 'cellular')
car_loan = (banking_array[:,5] == 'yes')
merg_cond = (conn) & (car_loan)
print("Count of cutomers who has connection and has taken car loan", np.count_nonzero(merg_cond))

Count of cutomers who has connection and has taken car loan 4


In [ ]:
# @title Task 4
# Find the count of customers with personal loan and are married and has car loan
cust_with_personal_loan = (banking_array[:,4] == 'yes')
car_loan = (banking_array[:,5] == 'yes')
married = (banking_array[:,2] == 'married')
merg_cond = (cust_with_personal_loan & car_loan & married)
print("Count of customers with personal loan and are married and has car loan", np.count_nonzero(merg_cond))

Count of customers with personal loan and are married and has car loan 4


In [ ]:
# @title Task 5
# Find the count of customers whose age is greater than 35 and less than 50 and also find the bank balance of these customers
age = (banking_array[:,0] > 35) & (banking_array[:,0] < 50)
overall_balance = (banking_array[:,3])
# Accessing total balance by age condition
cond = overall_balance[age]
print("Customers whose age is greater than 35 and less than 50 and the total bank balance of these customers is", cond.sum())
# np.count_nonzero(age)

Customers whose age is greater than 35 and less than 50 and the total bank balance of these customers is 13845.0


In [ ]:
# @title Task 6
# Find the count of customers whose profession is management and is married and has cellular connection

In [ ]:
# @title Task 7
# Find the count who are single but have more than average bank balance
single = (banking_array[:,2] == 'single')
balance = (banking_array[:,3])
avg_bal = np.mean(balance)
print("Average bank balance is", avg_bal)
cond = (single) & (balance > avg_bal)
print("Customers with balance greater than the average bank balance are", np.count_nonzero(cond))
banking_array[cond]

Average bank balance is 1442.0
Customers with balance greater than the average bank balance are 1


array([[37.0, 'admin.', 'single', 2317.0, 'yes', 'no', 'cellular', 'apr']],
      dtype=object)

In [ ]:
# @title Task 8
'''
Company has decided to give a bonus of 5% of their account balance to those account holders where age is more than or equal
to 55 years and whose account balance is more than 2000. Calculate the sum of the total bank balance to the account holders
after crediting thier bonus amount.
'''
age = (banking_array[:,0])
balance = (banking_array[:,3])
cond = (age >= 55) & (balance > 2000)
tot_bal = balance[cond]
bonus = 0.05 * tot_bal
tot_after_bonus = (tot_bal + bonus)
print("Sum of total bank balance to the account holders after crediting thier bonus amount is", tot_after_bonus)

Sum of total bank balance to the account holders after crediting thier bonus amount is [4276.65]


In [ ]:
# @title Task 9
'''
Company has decided if the age of the customer is less than 25 then his balance will be credited with 2000
and if it is above then credit 1000.
'''

'\nCompany has decided if the age of the customer is less than 25 then his balance will be credited with 2000\nand if it is above then credit 1000.\n'

# PANDAS

In [ ]:
# Importing pandas in python
import numpy as np
import pandas as pd

In [ ]:
# Series - Multiple rows but a single column.
# DataFrame - Multiple rows and multiple columns.

In [ ]:
# Creating a simple series
values = [100,200,300,400,500]
ser = pd.Series(values)
print(ser)

0    100
1    200
2    300
3    400
4    500
dtype: int64


In [ ]:
# Changing Index Value
values = [100,200,300,400,500]
ser = pd.Series(values, index = ['a','b','c','d','e'])
print(ser)

a    100
b    200
c    300
d    400
e    500
dtype: int64


In [ ]:
# Creating a Simple DataFrame
values = [100,200,300,400,500]
name = ['A1','A2','A3','A4','A5']

df = pd.DataFrame([name,values])

# Coverting horizontal row format into vertical column format
df = df.transpose()
df.columns = ['Name','Values']
print(df)

  Name Values
0   A1    100
1   A2    200
2   A3    300
3   A4    400
4   A5    500


# **Titanic Analysis**

In [ ]:
# Read CSV file into a DataFrame
import pandas as pd
df = pd.read_csv('Titanic.csv')
df
# To accept excel file
# df = pd.read_excel('file_name.xlsx')

PassengerId  Survived  Pclass  \
0            1.0       0.0     3.0   
1            2.0       1.0     1.0   
2            3.0       1.0     3.0   
3            4.0       1.0     1.0   
4            5.0       0.0     3.0   
..           ...       ...     ...   
994          NaN       NaN     NaN   
995          NaN       NaN     NaN   
996          NaN       NaN     NaN   
997          NaN       NaN     NaN   
998          NaN       NaN     NaN   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0    1.0   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0    1.0   
2                               Heikkinen, Miss. Laina  female  26.0    0.0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0    1.0   
4                             Allen, Mr. William Henry    male  35.0    0.0   
..                                                 ...     ...   ...    ...   
994                                                NaN     NaN   NaN    NaN   
995                                                NaN     NaN   NaN    NaN   
996                                                NaN     NaN   NaN    NaN   
997                                                NaN     NaN   NaN    NaN   
998                                                NaN     NaN   NaN    NaN   

     Parch            Ticket     Fare Cabin Embarked  
0      0.0         A/5 21171   7.2500   NaN        S  
1      0.0          PC 17599  71.2833   C85        C  
2      0.0  STON/O2. 3101282   7.9250   NaN        S  
3      0.0            113803  53.1000  C123        S  
4      0.0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
994    NaN               NaN      NaN   NaN      NaN  
995    NaN               NaN      NaN   NaN      NaN  
996    NaN               NaN      NaN   NaN      NaN  
997    NaN               NaN      NaN   NaN      NaN  
998    NaN               NaN      NaN   NaN      NaN  

[999 rows x 12 columns]

In [ ]:
# Shape Function (To get the count of rows and columns)
df.shape
# Rows
df.shape[0]
# Columns
df.shape[1]

12

In [ ]:
# To get the size of the dataset
df.size

11988

In [ ]:
# Describe function
df.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [ ]:
# Indexing of the Columns
df['Age']

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ... 
994     NaN
995     NaN
996     NaN
997     NaN
998     NaN
Name: Age, Length: 999, dtype: float64

In [ ]:
# Indexing more than one column
df[['Name','Age','Fare']]

Name   Age     Fare
0                              Braund, Mr. Owen Harris  22.0   7.2500
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0  71.2833
2                               Heikkinen, Miss. Laina  26.0   7.9250
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0  53.1000
4                             Allen, Mr. William Henry  35.0   8.0500
..                                                 ...   ...      ...
994                                                NaN   NaN      NaN
995                                                NaN   NaN      NaN
996                                                NaN   NaN      NaN
997                                                NaN   NaN      NaN
998                                                NaN   NaN      NaN

[999 rows x 3 columns]

In [ ]:
# Get the minimum value from Age column
df['Age'].max()

80.0

In [ ]:
# Get the maximum value from Age column
df['Age'].max()

80.0

In [ ]:
# Data Preprocessing
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 999 entries, 0 to 998
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    float64
 1   Survived     891 non-null    float64
 2   Pclass       891 non-null    float64
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    float64
 7   Parch        891 non-null    float64
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(7), object(5)
memory usage: 93.8+ KB


In [ ]:
# Checking null values
df.isnull()
df.isnull().sum()

PassengerId    108
Survived       108
Pclass         108
Name           108
Sex            108
Age            285
SibSp          108
Parch          108
Ticket         108
Fare           108
Cabin          795
Embarked       110
dtype: int64

In [ ]:
# Elimnating all the null values (i.e The entire row should be null)
df.dropna(how = 'all', inplace = True) # all means it will remove the null value if only the entire row is null
# df.dropna(how = 'any') # any means it will remove the null value if it finds even single cell to be null
# inplace = True (will permanently delete the null values)

In [ ]:
# Memory usage
df.memory_usage()

Index          7128
PassengerId    7128
Survived       7128
Pclass         7128
Name           7128
Sex            7128
Age            7128
SibSp          7128
Parch          7128
Ticket         7128
Fare           7128
Cabin          7128
Embarked       7128
dtype: int64

In [ ]:
# Checking the datatype of the columns
df['PassengerId'].dtype

dtype('float64')

In [ ]:
# Converting the datatype of a column
df[['PassengerId','Survived','SibSp','Parch','Pclass']] = df[['PassengerId','Survived','SibSp','Parch','Pclass']].astype('int16')

In [ ]:
# Printing the preview of the dataset
df.head(15)
df.tail(15)

ID                           Title      Genre            Director  \
985   986                   Your Highness  Adventure  David Gordon Green   
986   987             Final Destination 5     Horror        Steven Quale   
987   988                    Endless Love      Drama         Shana Feste   
988   989                         Martyrs     Horror      Pascal Laugier   
989   990                           Selma  Biography        Ava DuVernay   
990   991  Underworld: Rise of the Lycans     Action  Patrick Tatopoulos   
991   992                Taare Zameen Par      Drama          Aamir Khan   
992   993            Take Me Home Tonight     Comedy       Michael Dowse   
993   994        Resident Evil: Afterlife     Action  Paul W.S. Anderson   
994   995                       Project X     Comedy     Nima Nourizadeh   
995   996            Secret in Their Eyes      Crime           Billy Ray   
996   997                 Hostel: Part II     Horror            Eli Roth   
997   998          Step Up 2: The Streets      Drama          Jon M. Chu   
998   999                    Search Party  Adventure      Scot Armstrong   
999  1000                      Nine Lives     Comedy    Barry Sonnenfeld   

     Year  Runtime_minutes  Rating   Votes  Revenue_millions  
985  2011              102     5.6   87904             21.56  
986  2011               92     5.9   88000             42.58  
987  2014              104     6.3   33688             23.39  
988  2008               99     7.1   63785               NaN  
989  2014              128     7.5   67637             52.07  
990  2009               92     6.6  129708             45.80  
991  2007              165     8.5  102697              1.20  
992  2011               97     6.3   45419              6.92  
993  2010               97     5.9  140900             60.13  
994  2012               88     6.7  164088             54.72  
995  2015              111     6.2   27585               NaN  
996  2007               94     5.5   73152             17.54  
997  2008               98     6.2   70699             58.01  
998  2014               93     5.6    4881               NaN  
999  2016               87     5.3   12435             19.64

In [ ]:
# Removing Column from the Dataset
df.drop(['Ticket','Pclass'], axis = 1) # axis = 1 (column)

PassengerId  Survived                                               Name  \
0              1         0                            Braund, Mr. Owen Harris   
1              2         1  Cumings, Mrs. John Bradley (Florence Briggs Th...   
2              3         1                             Heikkinen, Miss. Laina   
3              4         1       Futrelle, Mrs. Jacques Heath (Lily May Peel)   
4              5         0                           Allen, Mr. William Henry   
..           ...       ...                                                ...   
886          887         0                              Montvila, Rev. Juozas   
887          888         1                       Graham, Miss. Margaret Edith   
888          889         0           Johnston, Miss. Catherine Helen "Carrie"   
889          890         1                              Behr, Mr. Karl Howell   
890          891         0                                Dooley, Mr. Patrick   

        Sex   Age  SibSp  Parch     Fare Cabin Embarked  
0      male  22.0      1      0   7.2500   NaN        S  
1    female  38.0      1      0  71.2833   C85        C  
2    female  26.0      0      0   7.9250   NaN        S  
3    female  35.0      1      0  53.1000  C123        S  
4      male  35.0      0      0   8.0500   NaN        S  
..      ...   ...    ...    ...      ...   ...      ...  
886    male  27.0      0      0  13.0000   NaN        S  
887  female  19.0      0      0  30.0000   B42        S  
888  female   NaN      1      2  23.4500   NaN        S  
889    male  26.0      0      0  30.0000  C148        C  
890    male  32.0      0      0   7.7500   NaN        Q  

[891 rows x 10 columns]

In [ ]:
# Removing Column from the Dataset
df.drop('Ticket', axis = 1, inplace = True) # axis = 1 (column)

In [ ]:
df.drop([0,2], axis = 0)

PassengerId  Survived  Pclass  \
1              2         1       1   
3              4         1       1   
4              5         0       3   
5              6         0       3   
6              7         0       1   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
5                                     Moran, Mr. James    male   NaN      0   
6                              McCarthy, Mr. Timothy J    male  54.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch     Fare Cabin Embarked  
1        0  71.2833   C85        C  
3        0  53.1000  C123        S  
4        0   8.0500   NaN        S  
5        0   8.4583   NaN        Q  
6        0  51.8625   E46        S  
..     ...      ...   ...      ...  
886      0  13.0000   NaN        S  
887      0  30.0000   B42        S  
888      2  23.4500   NaN        S  
889      0  30.0000  C148        C  
890      0   7.7500   NaN        Q  

[889 rows x 11 columns]

In [ ]:
# Renaming the column
df.rename(columns = {'Pclass':'Class'}, inplace = True)

In [ ]:
# Finding the unique values from the given column
print(pd.unique(df['Cabin']))

[nan 'C85' 'C123' 'E46' 'G6' 'C103' 'D56' 'A6' 'C23 C25 C27' 'B78' 'D33'
 'B30' 'C52' 'B28' 'C83' 'F33' 'F G73' 'E31' 'A5' 'D10 D12' 'D26' 'C110'
 'B58 B60' 'E101' 'F E69' 'D47' 'B86' 'F2' 'C2' 'E33' 'B19' 'A7' 'C49'
 'F4' 'A32' 'B4' 'B80' 'A31' 'D36' 'D15' 'C93' 'C78' 'D35' 'C87' 'B77'
 'E67' 'B94' 'C125' 'C99' 'C118' 'D7' 'A19' 'B49' 'D' 'C22 C26' 'C106'
 'C65' 'E36' 'C54' 'B57 B59 B63 B66' 'C7' 'E34' 'C32' 'B18' 'C124' 'C91'
 'E40' 'T' 'C128' 'D37' 'B35' 'E50' 'C82' 'B96 B98' 'E10' 'E44' 'A34'
 'C104' 'C111' 'C92' 'E38' 'D21' 'E12' 'E63' 'A14' 'B37' 'C30' 'D20' 'B79'
 'E25' 'D46' 'B73' 'C95' 'B38' 'B39' 'B22' 'C86' 'C70' 'A16' 'C101' 'C68'
 'A10' 'E68' 'B41' 'A20' 'D19' 'D50' 'D9' 'A23' 'B50' 'A26' 'D48' 'E58'
 'C126' 'B71' 'B51 B53 B55' 'D49' 'B5' 'B20' 'F G63' 'C62 C64' 'E24' 'C90'
 'C45' 'E8' 'B101' 'D45' 'C46' 'D30' 'E121' 'D11' 'E77' 'F38' 'B3' 'D6'
 'B82 B84' 'D17' 'A36' 'B102' 'B69' 'E49' 'C47' 'D28' 'E17' 'A24' 'C50'
 'B42' 'C148']


In [ ]:
# Titanic analysis
# Find the no.of male and feamale in the dataset
df['Sex'].value_counts().reset_index()

Sex  count
0    male    577
1  female    314

In [ ]:
# Loc and Iloc function
# Loc (location)
# Iloc (Index location)
df.iloc[0:100, 0:3] # Accesing first 100 rows and 3 columns
df.iloc[0:100, [0,3,-3]]
df.loc[0:100, ['PassengerId','Name','Fare']]

PassengerId                                               Name     Fare
0              1                            Braund, Mr. Owen Harris   7.2500
1              2  Cumings, Mrs. John Bradley (Florence Briggs Th...  71.2833
2              3                             Heikkinen, Miss. Laina   7.9250
3              4       Futrelle, Mrs. Jacques Heath (Lily May Peel)  53.1000
4              5                           Allen, Mr. William Henry   8.0500
..           ...                                                ...      ...
96            97                          Goldschmidt, Mr. George B  34.6542
97            98                    Greenfield, Mr. William Bertram  63.3583
98            99               Doling, Mrs. John T (Ada Julia Bone)  23.0000
99           100                                  Kantor, Mr. Sinai  26.0000
100          101                            Petranec, Miss. Matilda   7.8958

[101 rows x 3 columns]

In [ ]:
# Analysis of Titanic Dataset
# Find the no.of people with age greater than or equal to 18

# Step 1: Accessing the column
df['Age']
#Step 2: Applying the condition
df['Age'] >= 18
# Step 3: Wrapping the condition with df
len(df[df['Age'] >= 18])

601

In [ ]:
# Displaying all the rows with class 3 and age greater than 18
df[(df['Class'] == 3) & (df['Age'] > 18)]

PassengerId  Survived  Class  \
0              1         0      3   
2              3         1      3   
4              5         0      3   
8              9         1      3   
12            13         0      3   
..           ...       ...    ...   
881          882         0      3   
882          883         0      3   
884          885         0      3   
885          886         0      3   
890          891         0      3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
4                             Allen, Mr. William Henry    male  35.0      0   
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
12                      Saundercock, Mr. William Henry    male  20.0      0   
..                                                 ...     ...   ...    ...   
881                                 Markun, Mr. Johann    male  33.0      0   
882                       Dahlberg, Miss. Gerda Ulrika  female  22.0      0   
884                             Sutehall, Mr. Henry Jr    male  25.0      0   
885               Rice, Mrs. William (Margaret Norton)  female  39.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch     Fare Cabin Embarked  
0        0   7.2500   NaN        S  
2        0   7.9250   NaN        S  
4        0   8.0500   NaN        S  
8        2  11.1333   NaN        S  
12       0   8.0500   NaN        S  
..     ...      ...   ...      ...  
881      0   7.8958   NaN        S  
882      0  10.5167   NaN        S  
884      0   7.0500   NaN        S  
885      5  29.1250   NaN        Q  
890      0   7.7500   NaN        Q  

[261 rows x 11 columns]

In [ ]:
# Passenger should be either in Class 2 or Embarked S
df[(df['Class'] == 2) | (df['Embarked'] == 'S')]

PassengerId  Survived  Class  \
0              1         0      3   
2              3         1      3   
3              4         1      1   
4              5         0      3   
6              7         0      1   
..           ...       ...    ...   
883          884         0      2   
884          885         0      3   
886          887         0      2   
887          888         1      1   
888          889         0      3   

                                             Name     Sex   Age  SibSp  Parch  \
0                         Braund, Mr. Owen Harris    male  22.0      1      0   
2                          Heikkinen, Miss. Laina  female  26.0      0      0   
3    Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1      0   
4                        Allen, Mr. William Henry    male  35.0      0      0   
6                         McCarthy, Mr. Timothy J    male  54.0      0      0   
..                                            ...     ...   ...    ...    ...   
883                 Banfield, Mr. Frederick James    male  28.0      0      0   
884                        Sutehall, Mr. Henry Jr    male  25.0      0      0   
886                         Montvila, Rev. Juozas    male  27.0      0      0   
887                  Graham, Miss. Margaret Edith  female  19.0      0      0   
888      Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1      2   

        Fare Cabin Embarked  
0     7.2500   NaN        S  
2     7.9250   NaN        S  
3    53.1000  C123        S  
4     8.0500   NaN        S  
6    51.8625   E46        S  
..       ...   ...      ...  
883  10.5000   NaN        S  
884   7.0500   NaN        S  
886  13.0000   NaN        S  
887  30.0000   B42        S  
888  23.4500   NaN        S  

[664 rows x 11 columns]

In [ ]:
# Filter out all the data where Fare is less than 100 and Embarked should be either S or C
# df[(df['Fare'] < 100) & ((df['Embarked'] == 'S') | (df['Embarked'] == 'C'))]
df[(df['Fare'] < 100) & (df['Embarked'].isin(['S','C']))]

PassengerId  Survived  Class  \
0              1         0      3   
1              2         1      1   
2              3         1      3   
3              4         1      1   
4              5         0      3   
..           ...       ...    ...   
884          885         0      3   
886          887         0      2   
887          888         1      1   
888          889         0      3   
889          890         1      1   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
884                             Sutehall, Mr. Henry Jr    male  25.0      0   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   

     Parch     Fare Cabin Embarked  
0        0   7.2500   NaN        S  
1        0  71.2833   C85        C  
2        0   7.9250   NaN        S  
3        0  53.1000  C123        S  
4        0   8.0500   NaN        S  
..     ...      ...   ...      ...  
884      0   7.0500   NaN        S  
886      0  13.0000   NaN        S  
887      0  30.0000   B42        S  
888      2  23.4500   NaN        S  
889      0  30.0000  C148        C  

[759 rows x 11 columns]

In [ ]:
# Sorting function
df.sort_values(by = 'Age') # Ascending Order
df.sort_values(by = 'Age', ascending = False)

PassengerId  Survived  Class                                      Name  \
630          631         1      1      Barkworth, Mr. Algernon Henry Wilson   
851          852         0      3                       Svensson, Mr. Johan   
493          494         0      1                   Artagaveytia, Mr. Ramon   
96            97         0      1                 Goldschmidt, Mr. George B   
116          117         0      3                      Connors, Mr. Patrick   
..           ...       ...    ...                                       ...   
859          860         0      3                          Razi, Mr. Raihed   
863          864         0      3         Sage, Miss. Dorothy Edith "Dolly"   
868          869         0      3               van Melkebeke, Mr. Philemon   
878          879         0      3                        Laleff, Mr. Kristo   
888          889         0      3  Johnston, Miss. Catherine Helen "Carrie"   

        Sex   Age  SibSp  Parch     Fare Cabin Embarked  
630    male  80.0      0      0  30.0000   A23        S  
851    male  74.0      0      0   7.7750   NaN        S  
493    male  71.0      0      0  49.5042   NaN        C  
96     male  71.0      0      0  34.6542    A5        C  
116    male  70.5      0      0   7.7500   NaN        Q  
..      ...   ...    ...    ...      ...   ...      ...  
859    male   NaN      0      0   7.2292   NaN        C  
863  female   NaN      8      2  69.5500   NaN        S  
868    male   NaN      0      0   9.5000   NaN        S  
878    male   NaN      0      0   7.8958   NaN        S  
888  female   NaN      1      2  23.4500   NaN        S  

[891 rows x 11 columns]

In [ ]:
# Sorting function
df.sort_values(by = 'Fare') # Ascending Order
#df.sort_values(by = 'Fare', ascending = False)

PassengerId  Survived  Class                                Name     Sex  \
815          816         0      1                    Fry, Mr. Richard    male   
806          807         0      1              Andrews, Mr. Thomas Jr    male   
413          414         0      2      Cunningham, Mr. Alfred Fleming    male   
481          482         0      2    Frost, Mr. Anthony Wood "Archie"    male   
302          303         0      3     Johnson, Mr. William Cahoone Jr    male   
..           ...       ...    ...                                 ...     ...   
438          439         0      1                   Fortune, Mr. Mark    male   
341          342         1      1      Fortune, Miss. Alice Elizabeth  female   
737          738         1      1              Lesurer, Mr. Gustave J    male   
679          680         1      1  Cardeza, Mr. Thomas Drake Martinez    male   
258          259         1      1                    Ward, Miss. Anna  female   

      Age  SibSp  Parch      Fare        Cabin Embarked  
815   NaN      0      0    0.0000         B102        S  
806  39.0      0      0    0.0000          A36        S  
413   NaN      0      0    0.0000          NaN        S  
481   NaN      0      0    0.0000          NaN        S  
302  19.0      0      0    0.0000          NaN        S  
..    ...    ...    ...       ...          ...      ...  
438  64.0      1      4  263.0000  C23 C25 C27        S  
341  24.0      3      2  263.0000  C23 C25 C27        S  
737  35.0      0      0  512.3292         B101        C  
679  36.0      0      1  512.3292  B51 B53 B55        C  
258  35.0      0      0  512.3292          NaN        C  

[891 rows x 11 columns]

# IMDB Movie Data Analysis

In [ ]:
import pandas as pd
df = pd.read_csv('IMDBMovie.csv')
df

ID                    Title      Genre              Director  Year  \
0       1  Guardians of the Galaxy     Action            James Gunn  2014   
1       2               Prometheus  Adventure          Ridley Scott  2012   
2       3                    Split     Horror    M. Night Shyamalan  2016   
3       4                     Sing  Animation  Christophe Lourdelet  2016   
4       5            Suicide Squad     Action            David Ayer  2016   
..    ...                      ...        ...                   ...   ...   
995   996     Secret in Their Eyes      Crime             Billy Ray  2015   
996   997          Hostel: Part II     Horror              Eli Roth  2007   
997   998   Step Up 2: The Streets      Drama            Jon M. Chu  2008   
998   999             Search Party  Adventure        Scot Armstrong  2014   
999  1000               Nine Lives     Comedy      Barry Sonnenfeld  2016   

     Runtime_minutes  Rating   Votes  Revenue_millions  
0                121     8.1  757074            333.13  
1                124     7.0  485820            126.46  
2                117     7.3  157606            138.12  
3                108     7.2   60545            270.32  
4                123     6.2  393727            325.02  
..               ...     ...     ...               ...  
995              111     6.2   27585               NaN  
996               94     5.5   73152             17.54  
997               98     6.2   70699             58.01  
998               93     5.6    4881               NaN  
999               87     5.3   12435             19.64  

[1000 rows x 9 columns]

In [ ]:
# Shape function
df.shape

(1000, 9)

In [ ]:
# Size function
df.size

9000

In [ ]:
# Describe function
df.describe()

ID         Year  Runtime_minutes       Rating         Votes  \
count  1000.000000  1000.000000      1000.000000  1000.000000  1.000000e+03   
mean    500.500000  2012.783000       113.172000     6.723200  1.698083e+05   
std     288.819436     3.205962        18.810908     0.945429  1.887626e+05   
min       1.000000  2006.000000        66.000000     1.900000  6.100000e+01   
25%     250.750000  2010.000000       100.000000     6.200000  3.630900e+04   
50%     500.500000  2014.000000       111.000000     6.800000  1.107990e+05   
75%     750.250000  2016.000000       123.000000     7.400000  2.399098e+05   
max    1000.000000  2016.000000       191.000000     9.000000  1.791916e+06   

       Revenue_millions  
count        872.000000  
mean          82.956376  
std          103.253540  
min            0.000000  
25%           13.270000  
50%           47.985000  
75%          113.715000  
max          936.630000

In [ ]:
# Info of the dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   ID                1000 non-null   int64  
 1   Title             1000 non-null   object 
 2   Genre             1000 non-null   object 
 3   Director          1000 non-null   object 
 4   Year              1000 non-null   int64  
 5   Runtime_minutes   1000 non-null   int64  
 6   Rating            1000 non-null   float64
 7   Votes             1000 non-null   int64  
 8   Revenue_millions  872 non-null    float64
dtypes: float64(2), int64(4), object(3)
memory usage: 70.4+ KB


In [ ]:
# Checking null values
df.isnull().sum()

ID                    0
Title                 0
Genre                 0
Director              0
Year                  0
Runtime_minutes       0
Rating                0
Votes                 0
Revenue_millions    128
dtype: int64

In [ ]:
# Find the unique genre
print(pd.unique(df['Genre']))

['Action' 'Adventure' 'Horror' 'Animation' 'Comedy' 'Biography' 'Drama'
 'Crime' 'Romance' 'Mystery' 'Thriller' 'Sci-Fi' 'Fantasy']


In [ ]:
# Find the number of movies according to thier genre
df['Genre'].value_counts(ascending = True).reset_index()

Genre  count
0     Romance      2
1      Sci-Fi      3
2     Fantasy      4
3    Thriller     10
4     Mystery     13
5      Horror     46
6   Animation     49
7   Biography     64
8       Crime     71
9   Adventure     75
10     Comedy    175
11      Drama    195
12     Action    293